version: "3"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  
  node:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c 'python3 node.py'
    depends_on:
      - redis
    #   - db
    volumes:
      - ./app/:/app/
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 2m
    env_file:
      - .env
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./frontend/:/app/
    stop_signal: SIGINT
    stop_grace_period: 2m
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c 'uvicorn api:app --port 8000 --host 0.0.0.0'
    volumes:
      - ./app/:/app/
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 2m
    env_file:
      - .env
  
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - api
      - frontend
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build/:/var/www/app/frontend/
    ports:
      - "127.0.0.1:8000:8000"

volumes:
  redis_data:
    external: false
