version: "3"

services:
  node1:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c 'python3 node.py -n1'
    volumes:
      - ./app/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 1m
    env_file:
      - .env

  node2:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c 'python3 node.py -n2'
    volumes:
      - ./app/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 1m
    env_file:
      - .env

  node3:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c 'python3 node.py -n3'
    volumes:
      - ./app/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 1m
    env_file:
      - .env
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./frontend/:/app/
    stop_signal: SIGINT
    stop_grace_period: 2m
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: bash -c 'uvicorn api:app --port 8000 --host 0.0.0.0'
    volumes:
      - ./app/:/app/
    restart: always
    stop_signal: SIGINT
    stop_grace_period: 2m
    env_file:
      - .env
  
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - api
      - frontend
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build/:/var/www/app/frontend/
    ports:
      - "127.0.0.1:8000:8000"

